### ISSUE TITLE
osg_parse adds an extra 0 to northing coordinate

### ISSUE THREAD

**Issue by btojenniferborder** [cvitolo/r_rnrfa#13]
I tried using osg_parse for some 10 figure grid references, e.g.: TF4995917674, but it added an extra zero onto the northing so the points were in the wrong location (somewhere near Iceland rather than in East England). So TF4995917674 gave easting = 549959 and northing=3176740 rather than 317674

**Comment by cvitolo** [comment]
Thanks @btojenniferborder for reporting this.
It seems fixed now.

When I run
> rnrfa::osg_parse("TF4995917674")
>$easting
>[1] 549959
>$northing
>[1] 317674

The result is as expected.

**Comment by NatrixRW** [comment]
I am having the same issue, with Eastings and Northings having an extra '0' on the end. As an example, the first two grid reference in a test dataset are **SU8764039506** and **SU8762439543**. Running _osg_parse_ on these gives me:
```
$easting
4876400 4876240
$northing
1395060 1395430
```

But, if I run a test subset by creating a vector, the correct outputs are produced:

```
test_dat <- c("SU8764039506", "SU8762439543")
x <- osg_parse(test_dat)
x
$easting
[1] 487640 487624
$northing
[1] 139506 139543
```

**Comment by cvitolo** [comment]
Hi @NatrixRW , I cannot reproduce the issue above. Can you
Are you using the latest version of rnrfa?

**Comment by NatrixRW** [comment]
> Hi @NatrixRW , I cannot reproduce the issue above. Can you
> Are you using the latest version of rnrfa?

Hi @cvitolo. Yes I still have the same issue. I am using version 2.0.1.

**Comment by cvitolo** [comment]
Could you please provide a reproducible example? Many thanks!

**Comment by cvitolo** [comment]
Hi @NatrixRW , the fix is available in the latest version (2.0.2).
Please install it using the following command:

 `devtools::install_github("cvitolo/rnrfa")`

**Comment by NatrixRW** [comment]
Thanks I will test it out.
